SectionPagesMenu = "main"
baseURL = "/"
languageCode = "en-us"
title = "Aardvark Bark"
assetDir = "static"
summaryLength = 50
[[menu.mainnav]]
identifier = "products"
name = "Products"
url = "/products/"
weight = 2
[[menu.mainnav]]
identifier = "map"
name = "Map"
url = "/map/"
weight = 6
[[menu.mainnav]]
identifier = "calculator"
name = "Calculator"
url = "/calculator/"
weight = 5
[[menu.mainnav]]
identifier = "info"
name = "More Info"
url = "/info/"
weight = 4
[[menu.mainnav]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 3
[[menu.mainnav]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
