baseURL = "/"
languageCode = "en-us"
title = "Aardvark Bark"
SectionPagesMenu = "main"
[menu]

  [[menu.main]]
    identifier = "calculator"
    name = "Calculator"
    url = "/calculator/"
    weight = 100
    
summaryLength = 50
cloudinary_url = "https://res.cloudinary.com/aardvarkbark/image/upload"
thumb_med = "/t_thumb_med/"
aspect_400 = "/ar_16:9,c_crop,w_400/"
