SectionPagesMenu = "main"
baseURL = "/"
languageCode = "en-us"
title = "Aardvark Bark"
aspect_400 = "/ar_16:9,c_crop,w_400/"
cloudinary_url = "https://res.cloudinary.com/aardvarkbark/image/upload"
summaryLength = 50
thumb_med = "/t_thumb_med/"
[[menu.mainnav]]
identifier = "map"
name = "Map"
url = "/map/"
weight = 6
[[menu.mainnav]]
identifier = "calculator"
name = "Calculator"
url = "/calculator/"
weight = 5
[[menu.mainnav]]
identifier = "info"
name = "More Info"
url = "/info/"
weight = 4
[[menu.mainnav]]
identifier = "services"
name = "Services"
url = "/services/"
weight = 3
[[menu.mainnav]]
identifier = "products"
name = "Products"
url = "/products/"
weight = 2
[[menu.mainnav]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

