---
label: Products
hide_body: false
fields:
- type: text
  name: name
  label: Name
  config:
    required: false
  hidden: true
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
- type: file
  name: thumbnail
  label: Thumbnail
- type: boolean
  name: blower_truck
  label: Blower Truck?
  description: Can this product be used in a blower truck?
- type: boolean
  name: slinger_truck
  label: Slinger Truck?
  description: Can this product be used in a slinger truck?
pages:
- content/products/slinger-truck-only.md
- content/products/medium-red-bark.md
- content/products/fine-dark-bark.md
