---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
- type: file
  name: thumbnail
  label: Thumbnail
pages:
- content/products/medium-red-bark.md
- content/products/blown-dirt.md
- content/products/slinger-truck-only.md
- content/products/fine-dark-bark.md
