---
label: Products
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
- type: file
  name: thumbnail
  label: Thumbnail
- type: tag_list
  name: keywords
  label: Keywords
  description: For products, enter "slinger" and/or "blower" to relate
  default:
  - slinger
  - blower
pages:
- content/products/blown-dirt.md
- content/products/fine-dark-bark-1.md
- content/products/fine-dark-bark-2.md
- content/products/fine-dark-bark.md
- content/products/medium-red-bark-1.md
- content/products/medium-red-bark-2.md
- content/products/medium-red-bark.md
- content/products/pea-gravel.md
- content/products/roof-top-soil-mix.md
- content/products/slinger-truck-only.md
- content/products/wood-chip-mulch.md
