---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: thumbnail
  label: thumbnail
- type: tag_list
  name: keywords
  label: Keywords
  description: Similar keywords will show similar pages.
pages:
- content/services/play-chips.md
- content/services/slinger-truck.md
- content/services/blower-truck.md
